version: '2.2'

networks:
  edumeet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24

services:

  prometheus:
    image: prom/prometheus:v2.27.1
    user: root
    container_name: wst_prometheus
    restart: unless-stopped
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./data/prometheus:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    ports:
    - 9090:9090
    links:
    - node-exporter:node-exporter
    - pushgateway:pushgateway

  node-exporter:
    image: prom/node-exporter:v1.1.2
    container_name: wst_node_exporter
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway:v1.4.1
    container_name: wst_pushgateway
    restart: unless-stopped
    ports:
    - 9091:9091

  grafana:
    image: grafana/grafana:8.0.2
    user: root
    container_name: wst_grafana
    restart: unless-stopped
    links:
    - prometheus:prometheus
    ports:
    - 3000:3000
    volumes:
    - ./config/grafana-prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    - ./config/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
    - ./config/grafana-dashboards:/var/lib/grafana/dashboards
    - ./data/grafana:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
